// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgContent.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Content struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ParamId              int32    `protobuf:"varint,3,opt,name=param_id,json=paramId,proto3" json:"param_id,omitempty"`
	ParamString          string   `protobuf:"bytes,4,opt,name=param_string,json=paramString,proto3" json:"param_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ebc832082b9679, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Content) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Content) GetParamId() int32 {
	if m != nil {
		return m.ParamId
	}
	return 0
}

func (m *Content) GetParamString() string {
	if m != nil {
		return m.ParamString
	}
	return ""
}

type BackContent struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 int32     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Auth                 *Auth     `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Showroom             *ShowRoom `protobuf:"bytes,5,opt,name=showroom,proto3" json:"showroom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BackContent) Reset()         { *m = BackContent{} }
func (m *BackContent) String() string { return proto.CompactTextString(m) }
func (*BackContent) ProtoMessage()    {}
func (*BackContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ebc832082b9679, []int{1}
}

func (m *BackContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackContent.Unmarshal(m, b)
}
func (m *BackContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackContent.Marshal(b, m, deterministic)
}
func (m *BackContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackContent.Merge(m, src)
}
func (m *BackContent) XXX_Size() int {
	return xxx_messageInfo_BackContent.Size(m)
}
func (m *BackContent) XXX_DiscardUnknown() {
	xxx_messageInfo_BackContent.DiscardUnknown(m)
}

var xxx_messageInfo_BackContent proto.InternalMessageInfo

func (m *BackContent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BackContent) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BackContent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BackContent) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *BackContent) GetShowroom() *ShowRoom {
	if m != nil {
		return m.Showroom
	}
	return nil
}

type Auth struct {
	IsOk                 bool      `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	UseInfo              *Userinfo `protobuf:"bytes,2,opt,name=useInfo,proto3" json:"useInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ebc832082b9679, []int{2}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func (m *Auth) GetUseInfo() *Userinfo {
	if m != nil {
		return m.UseInfo
	}
	return nil
}

type ShowRoom struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	RoomsAndIds          string   `protobuf:"bytes,2,opt,name=roomsAndIds,proto3" json:"roomsAndIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRoom) Reset()         { *m = ShowRoom{} }
func (m *ShowRoom) String() string { return proto.CompactTextString(m) }
func (*ShowRoom) ProtoMessage()    {}
func (*ShowRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ebc832082b9679, []int{3}
}

func (m *ShowRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRoom.Unmarshal(m, b)
}
func (m *ShowRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRoom.Marshal(b, m, deterministic)
}
func (m *ShowRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRoom.Merge(m, src)
}
func (m *ShowRoom) XXX_Size() int {
	return xxx_messageInfo_ShowRoom.Size(m)
}
func (m *ShowRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRoom proto.InternalMessageInfo

func (m *ShowRoom) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ShowRoom) GetRoomsAndIds() string {
	if m != nil {
		return m.RoomsAndIds
	}
	return ""
}

type Room struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomName             string   `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ebc832082b9679, []int{4}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type Userinfo struct {
	Nick                 string   `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	RoomId               int32    `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomName             string   `protobuf:"bytes,4,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Userinfo) Reset()         { *m = Userinfo{} }
func (m *Userinfo) String() string { return proto.CompactTextString(m) }
func (*Userinfo) ProtoMessage()    {}
func (*Userinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ebc832082b9679, []int{5}
}

func (m *Userinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Userinfo.Unmarshal(m, b)
}
func (m *Userinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Userinfo.Marshal(b, m, deterministic)
}
func (m *Userinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Userinfo.Merge(m, src)
}
func (m *Userinfo) XXX_Size() int {
	return xxx_messageInfo_Userinfo.Size(m)
}
func (m *Userinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Userinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Userinfo proto.InternalMessageInfo

func (m *Userinfo) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Userinfo) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Userinfo) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Userinfo) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func init() {
	proto.RegisterType((*Content)(nil), "protobuf.Content")
	proto.RegisterType((*BackContent)(nil), "protobuf.BackContent")
	proto.RegisterType((*Auth)(nil), "protobuf.Auth")
	proto.RegisterType((*ShowRoom)(nil), "protobuf.ShowRoom")
	proto.RegisterType((*Room)(nil), "protobuf.Room")
	proto.RegisterType((*Userinfo)(nil), "protobuf.Userinfo")
}

func init() { proto.RegisterFile("msgContent.proto", fileDescriptor_d7ebc832082b9679) }

var fileDescriptor_d7ebc832082b9679 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xb1, 0x6e, 0xc2, 0x30,
	0x10, 0x55, 0x20, 0x21, 0xe1, 0x52, 0x21, 0x64, 0x55, 0x55, 0xda, 0x89, 0x66, 0x62, 0xa8, 0x32,
	0xb4, 0x5b, 0x37, 0xe8, 0xd2, 0x2c, 0xad, 0x64, 0xd4, 0xb9, 0x0a, 0x71, 0x20, 0x16, 0xb2, 0x8f,
	0xc6, 0x8e, 0xf8, 0x94, 0xfe, 0x6e, 0xe5, 0x23, 0xa1, 0x30, 0x30, 0xf9, 0xbd, 0xbb, 0x77, 0x7e,
	0x77, 0x0f, 0xa6, 0xca, 0x6c, 0xdf, 0x50, 0xdb, 0x4a, 0xdb, 0x6c, 0xdf, 0xa0, 0x45, 0x16, 0xd1,
	0xb3, 0x6e, 0x37, 0xe9, 0x0f, 0x84, 0x5d, 0x8b, 0x4d, 0x60, 0x20, 0x45, 0xe2, 0xcd, 0xbc, 0x79,
	0xc0, 0x07, 0x52, 0xb0, 0x04, 0xc2, 0x12, 0x95, 0x2a, 0xb4, 0x48, 0x06, 0x33, 0x6f, 0x3e, 0xe6,
	0x3d, 0x65, 0xf7, 0x10, 0xed, 0x8b, 0xa6, 0x50, 0xdf, 0x52, 0x24, 0x43, 0xd2, 0x87, 0xc4, 0x73,
	0xc1, 0x1e, 0xe1, 0xe6, 0xd8, 0x32, 0xb6, 0x91, 0x7a, 0x9b, 0xf8, 0x34, 0x19, 0x53, 0x6d, 0x45,
	0xa5, 0xf4, 0xd7, 0x83, 0x78, 0x59, 0x94, 0xbb, 0x6b, 0xbe, 0x0c, 0xfc, 0x12, 0x45, 0x45, 0xa6,
	0x01, 0x27, 0xcc, 0xa6, 0x30, 0x54, 0x66, 0x4b, 0x66, 0x63, 0xee, 0x20, 0x4b, 0xc1, 0x2f, 0x5a,
	0x5b, 0x93, 0x41, 0xfc, 0x3c, 0xc9, 0xfa, 0x8b, 0xb2, 0x45, 0x6b, 0x6b, 0x4e, 0x3d, 0x96, 0x41,
	0x64, 0x6a, 0x3c, 0x34, 0x88, 0x2a, 0x09, 0x48, 0xc7, 0xfe, 0x75, 0xab, 0x1a, 0x0f, 0x1c, 0x51,
	0xf1, 0x93, 0x26, 0x7d, 0x07, 0xdf, 0x4d, 0xbb, 0x0d, 0xa4, 0xf9, 0xdc, 0xd1, 0x4e, 0x11, 0x27,
	0xcc, 0x9e, 0x20, 0x6c, 0x4d, 0x95, 0xeb, 0x0d, 0xd2, 0x62, 0x17, 0x5f, 0x7d, 0x99, 0xaa, 0x91,
	0x7a, 0x83, 0xbc, 0x97, 0xa4, 0x4b, 0x88, 0xfa, 0xff, 0xd9, 0x2d, 0x04, 0x25, 0xb6, 0xda, 0x76,
	0x27, 0x1e, 0x09, 0x9b, 0x41, 0xec, 0x3c, 0xcd, 0x42, 0x8b, 0x5c, 0x98, 0x2e, 0xe1, 0xf3, 0x52,
	0xfa, 0x0a, 0x3e, 0xcd, 0xdf, 0xc1, 0xc8, 0x95, 0xf3, 0x3e, 0xa3, 0x8e, 0xb1, 0x07, 0x88, 0x1c,
	0xfa, 0x28, 0x54, 0xd5, 0x8d, 0x9f, 0x78, 0x2a, 0x20, 0xea, 0x97, 0x72, 0xd7, 0x68, 0x59, 0x1e,
	0xaf, 0x19, 0x73, 0xc2, 0x2e, 0xcf, 0x56, 0x8a, 0x2e, 0x62, 0x07, 0xcf, 0x5c, 0x86, 0x57, 0x5d,
	0xfc, 0x4b, 0x97, 0xf5, 0x88, 0x12, 0x78, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x28, 0xc5, 0x9c,
	0xf8, 0x61, 0x02, 0x00, 0x00,
}
